# Generated by Django 5.1 on 2024-08-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_name_job_item_name_remove_job_approx_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='unassigned', max_length=20),
        ),
    ]
